### ISSUE TITLE
Should the system expose the question supporting voters to the voters?   

### ISSUE THREAD

**Issue by Suberri** [hasadna/open-shot#237] opened 2013-09-02 11:49 UTC

**Comment by gl1000007** [comment] 2013-09-02 12:26
If I got you right, then https://github.com/hasadna/open-shot/issues/153
This is the 2nd duplicate of that issue. Please close it too.

**Closed as completed** 2013-09-02 12:30 UTC

**Comment by Suberri** [comment] 2013-09-02 12:31
you r correct

On Mon, Sep 2, 2013 at 3:26 PM, Gilad L notifications@github.com wrote:

> If I got you right, then #153https://github.com/hasadna/open-shot/issues/153
> This is the 2nd duplicate of that issue. Please close it too.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/237#issuecomment-23657262
> .

## 

Cheers
Moshe
