### ISSUE TITLE
Default user location (מקום) 

### ISSUE THREAD

**Issue by Suberri** [hasadna/open-shot#152] opened 2013-08-18 22:10 UTC
On entering Open-Shot the location (מקום) should be set to the user location.

M

**Comment by daonb** [comment] 2013-08-19 07:08
the location should be the place where the user is voting. There's a chance
the user will be joining the site from his work place or any other place.

**Comment by Suberri** [comment] 2013-08-19 11:54
Agree!
My comment is in regard to the setup of the field for a registered user
that have already configured his voting location. It seems to me that when
a registered user logs in or enters the site the system should set the
location field to the user configured location.  At this point the system
leaves the field blank or an arbitrary location is been displayed

M

On Mon, Aug 19, 2013 at 10:08 AM, benny daon notifications@github.comwrote:

> the location should be the place where the user is voting. There's a chance
> the user will be joining the site from his work place or any other place.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/152#issuecomment-22854217
> .

## 

Cheers
Moshe

**Comment by gl1000007** [comment] 2013-08-19 14:01
Linking to a former discussion:
https://github.com/hasadna/open-shot/issues/136

In addition, what if a user explicitly wants to see nation-wide data, for instance by clicking on a link to the [main page](http://oshot.hasadna.org.il/)? From my perspective, this kind of setting arbitrarily decides for the user that all they need to see is _their_ locality.

I thought of a solution would help the user jump to their locality quickly, without automatically redirecting them to another page:

![default locality](https://f.cloud.github.com/assets/5072931/986343/041e968c-08d7-11e3-9643-7682c0cff140.png)

[source](https://docs.google.com/file/d/0B3yaQaorsX55d2trY0lraXFka0k/edit?usp=sharing)

**Comment by Suberri** [comment] 2013-08-19 14:34
The system does allow a user to see all the cataloged Qs&As (locally and
nation wide).
However, a user may only enter a Q when the location is set to his own
voting location.

M

On Mon, Aug 19, 2013 at 5:01 PM, Gilad L notifications@github.com wrote:

> Linking to a former discussion:
> #136 https://github.com/hasadna/open-shot/issues/136
> 
> In addition, what if a user explicitly wants to see nation-wide data, for
> instance by clicking on a link to the main pagehttp://oshot.hasadna.org.il/?
> From my perspective, this kind of setting arbitrarily decides for the user
> that all they need to see is _their_ locality.
> 
> I thought of a solution would help the user go to their locality quickly,
> without automatically redirecting them to another page:
> 
> [image: default locality]https://f.cloud.github.com/assets/5072931/986343/041e968c-08d7-11e3-9643-7682c0cff140.png
> 
> sourcehttps://docs.google.com/file/d/0B3yaQaorsX55d2trY0lraXFka0k/edit?usp=sharing
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/152#issuecomment-22873635
> .

## 

Cheers
Moshe

**Comment by gl1000007** [comment] 2013-08-19 15:29
@Suberri Yes but what you suggest is taking the user to their locality automatically, even if they not want to.
Moreover, this may make the nation-wide view hard to reach, because clicking on the workshop's logo would take the user to their locality instead of the **true** main page, which is nation wide.
In that case, users will have to enter the places list and then choose the line of dashes (or "בחרו יישוב"), which is a very counter-intuitive process.

And let's think for a moment that we check the referring URL when a user gets to homepage, in order to decide if the user has just entered the site, or came from another **internal** page. On the first case, we'll show their locality, and on the second case we'll show the nation-wide homepage. This also is not recommended, for it makes the system unexpected.

Regarding the Q entering thingy, it's already done. Now the ask button is shown only at the main page and the user's locality.

**Comment by Suberri** [comment] 2013-08-19 16:52
mmm.. interesting.
Could we agree that in most cases a user would mostly interested in his own
voting locality?
So maybe the locality default should be user-locality or the last locality
that the user visited.
My issue was also to ask a Q, I needed to first go to my locality which is
not so easy (to find Modiin in the big drop down list) and then enter my Q.
Another option is to have a button that sends the user to his voting
locality and maybe the Q thingy on each page but it will send the user to
his locality to enter the Q.

What do you think?
M

On Mon, Aug 19, 2013 at 6:29 PM, Gilad L notifications@github.com wrote:

> @Suberri https://github.com/Suberri Yes but what you suggest is taking
> the user to their locality automatically, even if they not want to.
> Moreover, this may make the nation-wide view hard to reach, because
> clicking on the workshop's logo would take the user to their locality
> instead of the _true_ main page, which is nation wide.
> In that case, users will have to enter the places list and then choose the
> line of dashes (or "בחרו יישוב"), which is a very counter-intuitive process.
> 
> And let's think for a moment that we check the referring URL when a user
> gets to homepage, in order to decide if the user has just entered the site,
> or came from another _internal_ page. On the first case, we'll show their
> locality, and on the second case we'll show the nation-wide homepage. This
> also is not recommended, for it makes the system unexpected.
> 
> Regarding the Q entering thingy, it's already done. Now the ask button is
> shown only at the main page and the user's locality.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/152#issuecomment-22880347
> .

## 

Cheers
Moshe

**Comment by lotan1** [comment] 2013-08-20 22:38
just a bit offtopic
On entering a day after first login user location and landing page should remain his user location

**Comment by gl1000007** [comment] 2013-08-29 17:31
First of all,
@Suberri , there is a search box in the locality list, especially for the case you describe. Try searching for Modiin after typing "מו".

Second,
In most sites, Clicking the logo leads to the main page of the site, which in our case is the nation-wide view, or "אא מעלה אבק" in the beta. No one can argue otherwise. Check **ANY** large site you can think of. **We just can't break that convention**.

So, what I think should be done:
- After login or registration **only**, take the user to their locality.
- When entering to the main page http://localshot.org.il either by typing the URL or by clicking on the logo, display "אא מעלה אבק".
- For all other pages, just display that page _without any redirections_.
- This ![default locality 2](https://f.cloud.github.com/assets/5072931/1051509/3dcca9b2-10cc-11e3-8dbc-2c2f05d513b3.png) should make navigating to both user locality and nation-wide view easy enough. This will make Modiin even closer!

**logo link should be fixed ASAP, as it significantly reduces the chances of seeing "אא מעלה אבק".**
.
.
.
_People,_ next time when you have difficulty operating the site, please report about the difficulty itself, instead of jumping straight to the solution. Of course you can offer solutions, but first Write about the problem. Many times, the solutions are simpler than you think. Communication, people.

**Comment by Suberri** [comment] 2013-08-30 07:00
GL,

Thank you for your detailed response.
Let me see if I can clearly communicate my point:

As a user of the site I would appreciate the ability to get to my locality,
from anywhere on the site, with a single click.

Cheers
Moshe

On Thu, Aug 29, 2013 at 8:31 PM, Gilad L notifications@github.com wrote:

> First of all,
> @Suberri https://github.com/Suberri , there is a search box in the
> locality list, especially for the case you describe. Try searching for
> Modiin after typing "מו".
> 
> Second,
> In most sites, Clicking the logo leads to the main page of the site, which
> in our case is the nation-wide view, or "אא מעלה אבק" in the beta. No one
> can argue otherwise. Check _ANY_ large site you can think of. _We just
> can't break that convention_.
> 
> So, what I think should be done:
> - After login or registration _only_, take the user to their locality.
> - When entering to the main page http://localshot.org.il either by
>   typing the URL or by clicking on the logo, display "אא מעלה אבק".
> - For all other pages, just display that page *without any redirections
>   *.
> - This [image: default locality 2]https://f.cloud.github.com/assets/5072931/1051509/3dcca9b2-10cc-11e3-8dbc-2c2f05d513b3.pngshould make navigating to both user locality and nation-wide view easy
>   enough. This will make Modiin even closer!
> 
> _logo link should be fixed ASAP, as it significantly reduces the chances
> of seeing "אא מעלה אבק"._
> .
> .
> .
> _People,_ next time when you have difficulty operating the site, please
> report about the difficulty itself, instead of jumping straight to the
> solution. Of course you can offer solutions, but first Write about the
> problem. Many times, the solutions are simpler than you think.
> Communication, people.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/152#issuecomment-23507482
> .

## 

Cheers
Moshe

**Comment by gl1000007** [comment] 2013-08-30 08:37
**ACTION ITEMS HERE**

@Suberri my last comment should address exactly this need, while trying to balance it with the need of other users to gain access to the main page.
On second thought, that layout is still problematic, as it contains duplication of the locality controls (2 lists). So, from my perspective, you _will_ have to suffer 2 clicks instead of 1, but the layout will be _waaaaay_ more simpler.

Take a look at this:
![default locality 3](https://f.cloud.github.com/assets/5072931/1056863/2b1f509e-1162-11e3-8120-1a80cedc03e5.png)
#211 

let me summarize:
- **logo link should be fixed ASAP, as it significantly reduces the chances of seeing "אא מעלה אבק".**
- After login or registration **only**, take the user to their locality.
- When entering to the main page http://localshot.org.il either by typing the URL or by clicking on the logo, display "אא מעלה אבק".
- For all other pages, just display that page _without any redirections_.
- Apply the layout above.

In my opinion, separate issues are not appropriate here. Whoever takes this, needs to do all of the items.
On the other hand, commits still can be separate. Whatever helps you stay organized.

@daonb @lotan1 this issue demands quick fixing (at least the logo link), please add it to the next milestone.

**Comment by Suberri** [comment] 2013-08-30 08:54
Gilad L

Thanks - this is much better then searching for my locality.

Another option if I may - include "My Locality" in the user drop down menu
(my page, edit my profile, logout)

Cheers
Moshe

On Fri, Aug 30, 2013 at 11:37 AM, Gilad L notifications@github.com wrote:

> @Suberri https://github.com/Suberri my last comment should address
> exactly this need, while trying to balance it with the need of other users
> to gain access to the main page.
> On second thought, that layout is still problematic, as it contains
> duplication of the locality controls (2 lists). So, from my perspective,
> you _will_ have to suffer 2 clicks instead of 1, but the layout will be *
> waaaaay\* more simpler.
> 
> Take a look at this:
> [image: default locality 3]https://f.cloud.github.com/assets/5072931/1056067/825a5d64-114d-11e3-9ae2-7b0a2431634f.png
> #211 https://github.com/hasadna/open-shot/issues/211
> 
> let me summarize:
> - _logo link should be fixed ASAP, as it significantly reduces the
>   chances of seeing "אא מעלה אבק"._
> - After login or registration _only_, take the user to their locality.
> - When entering to the main page http://localshot.org.il either by
>   typing the URL or by clicking on the logo, display "אא מעלה אבק".
> - For all other pages, just display that page *without any redirections
>   *.
> - Apply the layout above.
> 
> In my opinion, separate issues are not appropriate here. Whoever takes
> this, needs to do all of the items.
> On the other hand, commits still can be separate. Whatever helps you stay
> organized.
> 
> @daonb https://github.com/daonb @lotan1 https://github.com/lotan1this issue demands quick fixing (at least the logo link), please add it to
> the next milestone.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/152#issuecomment-23547668
> .

## 

Cheers
Moshe

**Comment by gl1000007** [comment] 2013-08-30 09:29
Possible, but not replacing the solution above.
You may open an issue for it.

**Comment by gl1000007** [comment] 2013-08-30 10:21
Changed my mind. This is technically possible, but still a duplicate.
More important reason, many users may completely miss the ability to view localities other than theirs, which is an important feature of the site, promoting nation-wide discussion about election issues.
(this mind-change is caused by the separate issues working method, which makes it difficult for systemic thinking)

**Comment by Suberri** [comment] 2013-08-30 16:13
GL,

"many users may completely miss the ability to view localities other than
theirs...promoting nation-wide discussion about election issues"
I agree.
Please note that if the user would like to come back his locality, he must
be wondering  in other localities or  nation-wide .

Another option to one click locality is to change the button "העלו
שאלה"  when the user is wondering outside of his locality.

Cheers and have a great weekend
Moshe

On Fri, Aug 30, 2013 at 1:21 PM, Gilad L notifications@github.com wrote:

> Changed my mind. This is technically possible, but still a duplicate.
> More important reason, many users may completely miss the ability to view
> localities other than theirs, which is an important feature of the site,
> promoting nation-wide discussion about election issues.
> (this mind-change is caused by the separate issues working method, which
> makes it difficult for systemic thinking)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/152#issuecomment-23552547
> .

## 

Cheers
Moshe

**Comment by gl1000007** [comment] 2013-08-30 17:30
**No, he's not,** because his locality is placed at the _shiny and glorious_ beginning of the localities menu.
The reason behind all of this is keeping locality related controls in one place, even with the heavy price (seriously!) of one more click.
ANY, I repeat - **ANY** option of selecting a locality apart from the localities menu (excluding links inside the content area of the page), is wrong, and probably will cause the universe to collapse into itself.
.
Excuse me, but this discussion is way too long. Somebody apply it already!

**Comment by lotan1** [comment] 2013-08-31 08:37
סחטיין על ההעמקה!
אשמח אם מישהו מכם יוכל להציג את החלופות הקיימות כרגע בדיון לעניין, אולי
בגוגל גרופ שמכותבים בו עוד כמה משתמשים.
שבת שלום!

2013/8/30 Gilad L notifications@github.com

**Comment by gl1000007** [comment] 2013-08-31 09:09
זה בדיוק הדבר ההפוך ממה שצריך לקרות עם הדיון הזה. זה נושא ממש קטן (יחסית לתמונה הכללית) ואנחנו סתם מנפחים אותו.
כבר נכתב מספיק, פה: https://github.com/hasadna/open-shot/issues/152
בוא נסמוך על חברי הצוות שמבינים אנגלית, ושיקראו ישירות משם. זה מספיק מפורט, אולי אפילו יותר מדי.
זהו, אמרתי וציירתי את כל מה שאני חושב על הנושא הזה, ומבחינתי הדבר הבא שצריך לקרות זה שמישהו יממש את זה. לא שום דבר אחר.
קדימה לממש!

**Comment by daonb** [comment] 2013-09-01 12:01
I still don't get this change and I don't have time to read this. If there's a change that needs to be made, state it clearly. The title of the issue: "On entering Open-Shot the location (מקום) should be set to the user location." is working fine now as registered users are redirected from home to their locality

**Closed as completed by daonb** 2013-09-01 12:01 UTC
Labels: enhancement

**Comment by gl1000007** [comment] 2013-09-01 12:20
This is a fundemental usability problem.
Action items are here:
https://github.com/hasadna/open-shot/issues/152#issuecomment-23547668
I took the time to explain it deeply, so if you have the time, still read it.

ב-1 בספט 2013, בשעה 15:01, benny daon notifications@github.com כתב/ה:

**Comment by daonb** [comment] 2013-09-01 12:52
then copy whatever is applicable to a new issues that clearly tells me what
needs to be done. You trust the coder to read too much text and he'll end
up draing his own conclusions.
Create a new issue with a clear title and description and I'll fix it.

Benny

On 1 September 2013 15:20, Gilad L notifications@github.com wrote:

> This is a fundemental usability problem.
> Action items are here:
> https://github.com/hasadna/open-shot/issues/152#issuecomment-23547668
> I took the time to explain it deeply, so if you have the time, still read
> it.
> 
> ב-1 בספט 2013, בשעה 15:01, benny daon notifications@github.com כתב/ה:
> 
> > I still don't get this change and I don't have time to read this. If
> > there's a change that needs to be made, state it clearly. The title of the
> > issue: "On entering Open-Shot the location (מקום) should be set to the user
> > location." is working fine now as registered users are redirected from home
> > to their locality
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/152#issuecomment-23623835
> .

## 

http://yeda.us/daonb

**Comment by gl1000007** [comment] 2013-09-02 06:37
these 3 new issues should be assigned to a milestone.

**Comment by gl1000007** [comment] 2013-09-09 07:49
Further to the last meeting (2 sep 2013), we decided:
- For now, we won't use a nation-wide view.
- The "main page" of each user is their locality page.
- As long as there is no nation-wide view, Current state is correct.

Now updating the 3 issues above to reflect these decisions. (Update: Finished)
**There's nothing to see here, Move along ;)**
